octave failed to check tr1/unordered_map
The ways it is checking tr1/unordered_map in "configure" is not correct
which will lead to something like:

error: use of class template std::unordered_map requires template arguments
        std::unordered_map map;
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/unordered_map:663:24: note: template is declared here
class _LIBCPP_TYPE_VIS unordered_map
                       ^

And if this checking failed, two macros will be defined simultaneously:

HAVE_UNORDERED_MAP and USE_UNORDERED_MAP_WITH_TR1

which will result failure of compiling ./src/DLD-FUNCTIONS/rand.cc
because these two macros conflict.